
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Archives: /archives

# can include these pages on the front
index_pages:
- index
- about
- contact

# feed
atom: /atom.xml

# Miscelaneous
favicon: /favicon.png

# loaded in the head
stylesheets:
  - /components/normalize-css/normalize.css
  - /css/style.css
